// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: round_timer

#include "../ui.h"

void ui_Configuration_screen_init(void)
{
ui_Configuration = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Configuration, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelHeadingConfiguration = lv_label_create(ui_Configuration);
lv_obj_set_width( ui_labelHeadingConfiguration, lv_pct(100));
lv_obj_set_height( ui_labelHeadingConfiguration, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelHeadingConfiguration, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_labelHeadingConfiguration,"Round Timer Configuration");
lv_obj_set_style_text_align(ui_labelHeadingConfiguration, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelHeadingConfiguration, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelGetReady = lv_label_create(ui_Configuration);
lv_obj_set_width( ui_labelGetReady, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelGetReady, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelGetReady, 20 );
lv_obj_set_y( ui_labelGetReady, 42 );
lv_label_set_text(ui_labelGetReady,"GET READY");

ui_labelWorkout = lv_label_create(ui_Configuration);
lv_obj_set_width( ui_labelWorkout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelWorkout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelWorkout, 20 );
lv_obj_set_y( ui_labelWorkout, 92 );
lv_label_set_text(ui_labelWorkout,"WORKOUT");

ui_labelRest = lv_label_create(ui_Configuration);
lv_obj_set_width( ui_labelRest, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelRest, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelRest, 20 );
lv_obj_set_y( ui_labelRest, 140 );
lv_label_set_text(ui_labelRest,"REST");

ui_textGetReady = lv_textarea_create(ui_Configuration);
lv_obj_set_width( ui_textGetReady, 65);
lv_obj_set_height( ui_textGetReady, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_textGetReady, -73 );
lv_obj_set_y( ui_textGetReady, -85 );
lv_obj_set_align( ui_textGetReady, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_textGetReady,5);
lv_textarea_set_text(ui_textGetReady,"00:00");
lv_textarea_set_placeholder_text(ui_textGetReady,"Placeholder...");
lv_textarea_set_one_line(ui_textGetReady,true);
lv_obj_add_state( ui_textGetReady, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_textGetReady, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_textGetReady, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_textGetReady, LV_SCROLLBAR_MODE_OFF);



ui_textWorkout = lv_textarea_create(ui_Configuration);
lv_obj_set_width( ui_textWorkout, 65);
lv_obj_set_height( ui_textWorkout, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_textWorkout, -73 );
lv_obj_set_y( ui_textWorkout, -36 );
lv_obj_set_align( ui_textWorkout, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_textWorkout,5);
lv_textarea_set_text(ui_textWorkout,"00:00");
lv_textarea_set_placeholder_text(ui_textWorkout,"Placeholder...");
lv_textarea_set_one_line(ui_textWorkout,true);
lv_obj_add_state( ui_textWorkout, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_textWorkout, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_textWorkout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_textWorkout, LV_SCROLLBAR_MODE_OFF);



ui_textRest = lv_textarea_create(ui_Configuration);
lv_obj_set_width( ui_textRest, 65);
lv_obj_set_height( ui_textRest, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_textRest, -73 );
lv_obj_set_y( ui_textRest, 12 );
lv_obj_set_align( ui_textRest, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_textRest,5);
lv_textarea_set_text(ui_textRest,"00:00");
lv_textarea_set_placeholder_text(ui_textRest,"Placeholder...");
lv_textarea_set_one_line(ui_textRest,true);
lv_obj_add_state( ui_textRest, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_textRest, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_textRest, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_textRest, LV_SCROLLBAR_MODE_OFF);



ui_btnForegroundReady = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnForegroundReady, 40);
lv_obj_set_height( ui_btnForegroundReady, 40);
lv_obj_set_x( ui_btnForegroundReady, 47 );
lv_obj_set_y( ui_btnForegroundReady, -85 );
lv_obj_set_align( ui_btnForegroundReady, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnForegroundReady, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnForegroundReady, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnForegroundWorkout = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnForegroundWorkout, 40);
lv_obj_set_height( ui_btnForegroundWorkout, 40);
lv_obj_set_x( ui_btnForegroundWorkout, 47 );
lv_obj_set_y( ui_btnForegroundWorkout, -36 );
lv_obj_set_align( ui_btnForegroundWorkout, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnForegroundWorkout, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnForegroundWorkout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnForegroundRest = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnForegroundRest, 40);
lv_obj_set_height( ui_btnForegroundRest, 40);
lv_obj_set_x( ui_btnForegroundRest, 47 );
lv_obj_set_y( ui_btnForegroundRest, 12 );
lv_obj_set_align( ui_btnForegroundRest, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnForegroundRest, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnForegroundRest, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnBackgroundReady = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnBackgroundReady, 40);
lv_obj_set_height( ui_btnBackgroundReady, 40);
lv_obj_set_x( ui_btnBackgroundReady, 98 );
lv_obj_set_y( ui_btnBackgroundReady, -85 );
lv_obj_set_align( ui_btnBackgroundReady, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnBackgroundReady, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnBackgroundReady, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnBackgroundWorkout = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnBackgroundWorkout, 40);
lv_obj_set_height( ui_btnBackgroundWorkout, 40);
lv_obj_set_x( ui_btnBackgroundWorkout, 98 );
lv_obj_set_y( ui_btnBackgroundWorkout, -36 );
lv_obj_set_align( ui_btnBackgroundWorkout, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnBackgroundWorkout, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnBackgroundWorkout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnBackgroundRest = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnBackgroundRest, 40);
lv_obj_set_height( ui_btnBackgroundRest, 40);
lv_obj_set_x( ui_btnBackgroundRest, 98 );
lv_obj_set_y( ui_btnBackgroundRest, 12 );
lv_obj_set_align( ui_btnBackgroundRest, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnBackgroundRest, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnBackgroundRest, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelConfigurationSelector = lv_label_create(ui_Configuration);
lv_obj_set_width( ui_labelConfigurationSelector, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelConfigurationSelector, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelConfigurationSelector, 26 );
lv_obj_set_y( ui_labelConfigurationSelector, 200 );
lv_label_set_text(ui_labelConfigurationSelector,"Choose a preset");

ui_btnConfig1 = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnConfig1, 50);
lv_obj_set_height( ui_btnConfig1, 50);
lv_obj_set_x( ui_btnConfig1, -212 );
lv_obj_set_y( ui_btnConfig1, 108 );
lv_obj_set_align( ui_btnConfig1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnConfig1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnConfig1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelConfig1 = lv_label_create(ui_btnConfig1);
lv_obj_set_width( ui_labelConfig1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelConfig1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelConfig1, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelConfig1,"1");

ui_btnConfig2 = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnConfig2, 50);
lv_obj_set_height( ui_btnConfig2, 50);
lv_obj_set_x( ui_btnConfig2, -157 );
lv_obj_set_y( ui_btnConfig2, 108 );
lv_obj_set_align( ui_btnConfig2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnConfig2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnConfig2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelConfig2 = lv_label_create(ui_btnConfig2);
lv_obj_set_width( ui_labelConfig2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelConfig2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelConfig2, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelConfig2,"2");

ui_btnConfig3 = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnConfig3, 50);
lv_obj_set_height( ui_btnConfig3, 50);
lv_obj_set_x( ui_btnConfig3, -101 );
lv_obj_set_y( ui_btnConfig3, 108 );
lv_obj_set_align( ui_btnConfig3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnConfig3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnConfig3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelConfig3 = lv_label_create(ui_btnConfig3);
lv_obj_set_width( ui_labelConfig3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelConfig3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelConfig3, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelConfig3,"3");

ui_btnStart = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnStart, 100);
lv_obj_set_height( ui_btnStart, 50);
lv_obj_set_x( ui_btnStart, 187 );
lv_obj_set_y( ui_btnStart, 108 );
lv_obj_set_align( ui_btnStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelStart = lv_label_create(ui_btnStart);
lv_obj_set_width( ui_labelStart, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelStart, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelStart, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelStart,"Start");

ui_btnSave = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnSave, 100);
lv_obj_set_height( ui_btnSave, 50);
lv_obj_set_x( ui_btnSave, 40 );
lv_obj_set_y( ui_btnSave, 108 );
lv_obj_set_align( ui_btnSave, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnSave, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelSave = lv_label_create(ui_btnSave);
lv_obj_set_width( ui_labelSave, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelSave, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelSave, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelSave,"Save");

ui_btnUp = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnUp, 40);
lv_obj_set_height( ui_btnUp, 40);
lv_obj_set_x( ui_btnUp, -4 );
lv_obj_set_y( ui_btnUp, -85 );
lv_obj_set_align( ui_btnUp, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelUp = lv_label_create(ui_btnUp);
lv_obj_set_width( ui_labelUp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelUp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelUp, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelUp,"+");

ui_btnDown = lv_btn_create(ui_Configuration);
lv_obj_set_width( ui_btnDown, 40);
lv_obj_set_height( ui_btnDown, 40);
lv_obj_set_x( ui_btnDown, -4 );
lv_obj_set_y( ui_btnDown, 12 );
lv_obj_set_align( ui_btnDown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelDown = lv_label_create(ui_btnDown);
lv_obj_set_width( ui_labelDown, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelDown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelDown, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelDown,"-");

}
