// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: round_timer

#include "../ui.h"

void ui_Color_Chooser_screen_init(void)
{
ui_Color_Chooser = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Color_Chooser, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelHeadingColor = lv_label_create(ui_Color_Chooser);
lv_obj_set_width( ui_labelHeadingColor, lv_pct(100));
lv_obj_set_height( ui_labelHeadingColor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelHeadingColor, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_labelHeadingColor,"Choose a Text Color");
lv_obj_set_style_text_align(ui_labelHeadingColor, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelHeadingColor, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnAcceptColor = lv_btn_create(ui_Color_Chooser);
lv_obj_set_width( ui_btnAcceptColor, 100);
lv_obj_set_height( ui_btnAcceptColor, 50);
lv_obj_set_x( ui_btnAcceptColor, 0 );
lv_obj_set_y( ui_btnAcceptColor, 108 );
lv_obj_set_align( ui_btnAcceptColor, LV_ALIGN_CENTER );
lv_obj_add_state( ui_btnAcceptColor, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_btnAcceptColor, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnAcceptColor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelAcceptColor = lv_label_create(ui_btnAcceptColor);
lv_obj_set_width( ui_labelAcceptColor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelAcceptColor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelAcceptColor, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelAcceptColor,"Accept");

}
