// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: round_timer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Configuration
void ui_Configuration_screen_init(void);
lv_obj_t *ui_Configuration;
lv_obj_t *ui_labelHeadingConfiguration;
lv_obj_t *ui_labelGetReady;
lv_obj_t *ui_labelWorkout;
lv_obj_t *ui_labelRest;
lv_obj_t *ui_textGetReady;
lv_obj_t *ui_textWorkout;
lv_obj_t *ui_textRest;
lv_obj_t *ui_btnForegroundReady;
lv_obj_t *ui_btnForegroundWorkout;
lv_obj_t *ui_btnForegroundRest;
lv_obj_t *ui_btnBackgroundReady;
lv_obj_t *ui_btnBackgroundWorkout;
lv_obj_t *ui_btnBackgroundRest;
lv_obj_t *ui_labelConfigurationSelector;
lv_obj_t *ui_btnConfig1;
lv_obj_t *ui_labelConfig1;
lv_obj_t *ui_btnConfig2;
lv_obj_t *ui_labelConfig2;
lv_obj_t *ui_btnConfig3;
lv_obj_t *ui_labelConfig3;
lv_obj_t *ui_btnStart;
lv_obj_t *ui_labelStart;
lv_obj_t *ui_btnSave;
lv_obj_t *ui_labelSave;
lv_obj_t *ui_btnUp;
lv_obj_t *ui_labelUp;
lv_obj_t *ui_btnDown;
lv_obj_t *ui_labelDown;


// SCREEN: ui_Color_Chooser
void ui_Color_Chooser_screen_init(void);
lv_obj_t *ui_Color_Chooser;
lv_obj_t *ui_labelHeadingColor;
lv_obj_t *ui_btnAcceptColor;
lv_obj_t *ui_labelAcceptColor;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Configuration_screen_init();
ui_Color_Chooser_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Configuration);
}
