# Basic continuous integration for scons rt-thread build
#    Copyright 2023 Thomas Reidemeister
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @author Thomas Reidemeister
name: ContinousIntegration

on:
  push:
    branches: [ ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_scons:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
          path: code

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y scons wget build-essential git
          # Get GNU ARM Tools 10.3.x
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          tar xvf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          export PATH=$PATH:$PWD/gcc-arm-none-eabi-10.3-2021.10/bin
          # Sanity check
          arm-none-eabi-gcc --version

      - name: Build project using scons
        run: |
          export PATH=$PATH:$PWD/gcc-arm-none-eabi-10.3-2021.10/bin
          cd code
          source ./envsetup.sh
          scons --verbose
